services:
  postgres:
    image: postgres:16
    container_name: lms_database
    environment:
      POSTGRES_DB: lmsdataextraction
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - lms_data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d

volumes:
  lms_data:
